### ISSUE TITLE
Question: Does the KEContact wallbox expose the 'battery charge status percentage'?

### ISSUE THREAD

**Issue by jpt60** [UncleSamSwiss/ioBroker.kecontact#3]
Hi,

This is not really an issue, but a question: Does the KeContact wallbox UDP interface expose the car's battery charge status? For example: "60% charged". I would like to query the charge percentage via UDP binding. Is that possible at all?

Cheers

**Comment by UncleSamSwiss** [comment]
Hi

According to the documentation by Keba, there is no way of knowing the charging state of your vehicle:
https://www.keba.com/web/downloads/e-mobility/KeContact_P20_UDP_ProgrGuide_en.pdf

My guess is, the charger itself does not even get this information from the vehicle, but only the allowed current with which it can charge.

Perhaps you have a  way of getting this information from your car - I guess you don't own a Tesla, because AFAIK they provide this information through their mobile app.

/UncleSam

**Comment by jpt60** [comment]
Hi UncleSam,

 

Many thanks for your helpful explanations. I feared that would be the case.

 

And I agree with you that manufacturer mobile apps are not the best way for the consumer, particularly if there is a monthly cost associated with it.

 

A somewhat related question: When the Keba has fully charged the car, what STATE does it broadcast? I couldn’t see a state relating to charging complete or similar. Does it broadcast a change of state at all?

 

Have a great day and kind regards,

Jpt60

**Comment by jpt60** [comment]
Hi again,

 

Looking at the kecontact.js code, I see that there is a port 7092 defined for var BROADCAST_UDP_PORT.

However,in the Keba UDP Guide it only mentions port 7090.

Why is the 7092 needed?

 

Cheers

Jpt60

**Comment by UncleSamSwiss** [comment]
Hi

Sorry for only getting back now. I hope you could figure this out yourself in the meantime.
As I personally don't own a Wallbox, I can't really test things myself; but I guess you figured out the right state.
Unfortunately the Keba documentation is rather spotty. Port 7092 is used for broadcasts - I had to figure this out myself.

/UncleSam
